### ISSUE TITLE
Cannot cast ufunc add output from dtype('int32') to dtype('uint8') with casting rule 'same_kind'

### ISSUE THREAD

**Issue by svezina** [matthewearl/faceswap#5] opened 2016-01-17 21:26 UTC
Hi Matthew,

Great piece of code. Thanks for putting this together from the Switching Eds blog post.

On line 197 inside correct_colours(), the following error happens on a x64 Windows 10 machine with Python 2.7.11:

im2_blur += 128 \* (im2_blur <= 1.0)
TypeError: Cannot cast ufunc add output from dtype('int32') to dtype('uint8') with casting rule 'same_kind'

Cheers

**Comment by matthewearl** [comment] 2016-01-19 11:17
Hi, I cannot reproduce the issue easily (my windows machine isn't set up for Python development).  Can you check if changing the failing line to the following fixes the issue?

```
im2_blur += (128 * (im2_blur <= 1.0)).astype(im2_blur.dtype)
```

**Comment by svezina** [comment] 2016-01-19 14:23
Yep, that did it. I just sent you a PR.
Thanks a lot

**Comment by matthewearl** [comment] 2016-01-19 14:25
Thanks for the PR, now merged.

**Closed as completed by matthewearl** 2016-01-19 14:25 UTC
